# resolver: lts-13.7   # original, ghc-8.6.3
resolver: lts-13.12    # oldest option for ghc-8.6.4
# resolver: lts-13.19  # newest option for ghc-8.6.4
# resolver: lts-13.20  # oldest option for ghc-8.6.5
# resolver: lts-14.7   # newest option for ghc-8.6.5

packages:
  - ./

extra-deps:
  - arrows-0.4.4.2
  - Stream-0.4.7.2
  - lazysmallcheck-0.6
  - HCodecs-0.5.1
  - PortMidi-0.1.6.1
