# resolver: lts-13.7   # original, ghc-8.6.3
# resolver: lts-13.12  # oldest option for ghc-8.6.4
# resolver: lts-13.19  # newest option for ghc-8.6.4
# resolver: lts-13.20  # oldest option for ghc-8.6.5
# resolver: lts-14.7   # newest option for ghc-8.6.5
# resolver: lts-15.0   # oldest option for ghc-8.8.2
# resolver: lts-15.3   # newest option for ghc-8.8.2
# resolver: lts-15.4   # oldest option for ghc-8.8.3
resolver: lts-16.3     # newest option for ghc-8.8.3

packages:
  - ./

extra-deps:
  - arrows-0.4.4.2
  - HCodecs-0.5.2
  - lazysmallcheck-0.6  # required by Stream
  - PortMidi-0.1.6.1
  - Stream-0.4.7.2      # required by arrows
